using Microsoft.VisualStudio.TestTools.UnitTesting;
using Neatoo.Samples.DomainModel.SourceGenerators;

namespace Neatoo.Samples.DomainModel.Tests.SourceGenerators;

/// <summary>
/// Tests for SourceGeneratorSamples.cs code snippets.
/// These tests verify that source generators produce working code.
/// </summary>
[TestClass]
[TestCategory("Documentation")]
[TestCategory("SourceGenerators")]
public class SourceGeneratorSamplesTests : SamplesTestBase
{
    [TestInitialize]
    public void TestInitialize()
    {
        InitializeScope();
    }

    #region Product Tests - Verify Generated Factory

    [TestMethod]
    public void Product_FactoryGenerated_CreateMethodExists()
    {
        // Arrange & Act - Factory interface and Create method should be generated
        var factory = GetRequiredService<IProductFactory>();
        var product = factory.Create();

        // Assert
        Assert.IsNotNull(product);
    }

    [TestMethod]
    public void Product_FactoryGenerated_FetchMethodExists()
    {
        // Arrange
        var factory = GetRequiredService<IProductFactory>();

        // Act
        var product = factory.Fetch(1, "Test Product", 29.99m, 100);

        // Assert
        Assert.IsNotNull(product);
        Assert.AreEqual(1, product.Id);
        Assert.AreEqual("Test Product", product.Name);
        Assert.AreEqual(29.99m, product.Price);
        Assert.AreEqual(100, product.StockCount);
    }

    [TestMethod]
    public async Task Product_FactoryGenerated_SaveMethodExists()
    {
        // Arrange
        var factory = GetRequiredService<IProductFactory>();
        var product = factory.Create();
        product.Name = "New Product";
        product.Price = 19.99m;
        product.StockCount = 50;

        // Act - Save method should be generated because entity has [Insert] and [Update]
        var saved = await factory.Save(product);

        // Assert
        Assert.IsNotNull(saved);
    }

    #endregion

    #region Property Generation Tests

    [TestMethod]
    public void Product_PartialProperties_TrackModification()
    {
        // Arrange
        var factory = GetRequiredService<IProductFactory>();
        var product = factory.Fetch(1, "Original", 10m, 5);

        // Assert initial state
        Assert.IsFalse(product.IsModified);

        // Act - Modify a partial property
        product.Name = "Modified";

        // Assert - Modification tracking works (generated by source generator)
        Assert.IsTrue(product.IsModified);
        Assert.IsTrue(product[nameof(product.Name)].IsModified);
    }

    [TestMethod]
    public void Product_PartialProperties_HaveMetaPropertyAccess()
    {
        // Arrange
        var factory = GetRequiredService<IProductFactory>();
        var product = factory.Create();

        // Act & Assert - Meta-property access works (generated by source generator)
        var nameProp = product[nameof(product.Name)];
        Assert.IsNotNull(nameProp);
        Assert.AreEqual("Product Name", nameProp.DisplayName); // From [DisplayName]
    }

    [TestMethod]
    public void Product_PartialProperties_ValidationWorks()
    {
        // Arrange
        var factory = GetRequiredService<IProductFactory>();
        var product = factory.Create();

        // Act - Set empty name (violates [Required])
        product.Name = "";

        // Assert - Validation from attribute works
        Assert.IsFalse(product[nameof(product.Name)].IsValid);
    }

    #endregion

    #region Minimal Entity Tests

    [TestMethod]
    public void MinimalEntity_FactoryGenerated_Works()
    {
        // Arrange & Act - Even minimal entity gets factory generated
        var factory = GetRequiredService<IMinimalEntityFactory>();
        var entity = factory.Create();

        // Assert
        Assert.IsNotNull(entity);
    }

    #endregion
}
