using DomainModel;
using KnockOff;
using Person.Dal;

namespace DomainModel.Tests.UnitTests;

[KnockOff]
internal partial class PersonPhoneListFactoryStub : IPersonPhoneListFactory
{
    // Internal interface members visible via InternalsVisibleTo — not generated by KnockOff
    IPersonPhoneList IPersonPhoneListFactory.Fetch(IEnumerable<PersonPhoneEntity> personPhoneEntities, CancellationToken cancellationToken)
        => throw new NotImplementedException("Internal Fetch overload not used in unit tests");

    IPersonPhoneList IPersonPhoneListFactory.Save(IPersonPhoneList target, ICollection<PersonPhoneEntity> personPhoneEntities, CancellationToken cancellationToken)
        => target;
}
