using Neatoo;
using Neatoo.RemoteFactory;
using Person.Ef;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DomainModel;

public enum PhoneType
{
    Home,
    Work,
    Mobile
}

public partial interface IPersonPhone : IIdEditBase
{
    // Additional Properties auto-generated by BaseGenerator (Roslyn)
    internal IPerson? ParentPerson { get; }
}

[Factory]
internal partial class PersonPhone : IdEditBase<PersonPhone>, IPersonPhone
{
    [Create]
    public PersonPhone([Service] IUniquePhoneNumberRule uniquePhoneNumberRule,
                    [Service] IUniquePhoneTypeRule uniquePhoneTypeRule,
        [Service] IEditBaseServices<PersonPhone> services) : base(services)
    {
        RuleManager.AddRule(uniquePhoneNumberRule);
        RuleManager.AddRule(uniquePhoneTypeRule);
    }

    [Required(ErrorMessage = "Phone number type is required")]
    public partial PhoneType? PhoneType { get; set; }

    [DisplayName("Phone Number*")]
    [Required(ErrorMessage = "Phone number is required")]
    public partial string? PhoneNumber { get; set; }

    public IPerson? ParentPerson => this.Parent as IPerson;

    public partial void MapFrom(PersonPhoneEntity personPhoneEntity);
    public partial void MapTo(PersonPhoneEntity personPhoneEntity);

    [Fetch]
    public void Fetch(PersonPhoneEntity personPhoneEntity)
    {
        MapFrom(personPhoneEntity);
    }

    [Insert]
    [Update]
    public void Update(PersonPhoneEntity personPhoneEntity)
    {
        MapTo(personPhoneEntity);

        if(Id == null)
        {
            personPhoneEntity.PropertyChanged += HandleIdPropertyChanged;
        }
    }
}