using Neatoo;
using Neatoo.RemoteFactory;
using Person.Ef;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DomainModel;

public partial interface IPerson : IEntityBase
{
    // Not Empty - Properties auto-generated by BaseGenerator (Roslyn)
}

[Factory]
[AuthorizeFactory<IPersonAuth>]
internal partial class Person : EntityBase<Person>, IPerson
{
    public Person(IEntityBaseServices<Person> editBaseServices,
                  IUniqueNameRule uniqueNameRule) : base(editBaseServices)
    {
        RuleManager.AddRule(uniqueNameRule);
    }

    public partial Guid? Id { get; set; }

    [DisplayName("First Name*")]
    [Required(ErrorMessage = "First Name is required")]
    public partial string? FirstName { get; set; }

    [DisplayName("Last Name*")]
    [Required(ErrorMessage = "Last Name is required")]
    public partial string? LastName { get; set; }

    [DisplayName("Email Address")]
    public partial string? Email { get; set; }

    [DisplayName("Notes")]
    public partial string? Notes { get; set; }

    public partial IPersonPhoneList PersonPhoneList { get; set; }

    public void MapFrom(PersonEntity personEntity)
    {
        this.Id = personEntity.Id;
        this.FirstName = personEntity.FirstName;
        this.LastName = personEntity.LastName;
        this.Email = personEntity.Email;
        this.Notes = personEntity.Notes;
    }

    public void MapTo(PersonEntity personEntity)
    {
        personEntity.Id = this.Id;
        personEntity.FirstName = this.FirstName ?? throw new NullReferenceException("Person.FirstName");
        personEntity.LastName = this.LastName ?? throw new NullReferenceException("Person.LastName");
        personEntity.Email = this.Email;
        personEntity.Notes = this.Notes;
    }

    public partial void MapModifiedTo(PersonEntity personEntity);

    [Create]
    public void Create([Service] IPersonPhoneList personPhoneModelList)
    {
        PersonPhoneList = personPhoneModelList;
    }

    [Remote]
    [Fetch]
    public async Task<bool> Fetch([Service] IPersonDbContext personContext,
                                    [Service] IPersonPhoneListFactory personPhoneModelListFactory)
    {
        var personEntity = await personContext.FindPerson();
        if (personEntity == null)
        {
            return false;
        }
        this.MapFrom(personEntity);
        this.PersonPhoneList = personPhoneModelListFactory.Fetch(personEntity.Phones);
        return true;
    }

    [Remote]
    [Insert]
    public async Task<PersonEntity?> Insert([Service] IPersonDbContext personContext,
                                    [Service] IPersonPhoneListFactory personPhoneModelListFactory)
    {
        await RunRules();

        if(!this.IsSavable)
        {
            return null;
        }

        this.Id = Guid.NewGuid();

        var personEntity = new PersonEntity();
        this.MapTo(personEntity);
        personContext.AddPerson(personEntity);

        personPhoneModelListFactory.Save(this.PersonPhoneList, personEntity.Phones);

        await personContext.SaveChangesAsync();
        return personEntity;
    }

    [Remote]
    [Update]
    public async Task<PersonEntity?> Update([Service] IPersonDbContext personContext,
                                    [Service] IPersonPhoneListFactory personPhoneModelListFactory)
    {
        await RunRules();

        if (!this.IsSavable)
        {
            return null;
        }

        var personEntity = await personContext.FindPerson(this.Id);
        if (personEntity == null)
        {
            throw new KeyNotFoundException("Person not found");
        }

        this.MapModifiedTo(personEntity);

        personPhoneModelListFactory.Save(this.PersonPhoneList, personEntity.Phones);

        await personContext.SaveChangesAsync();
        return personEntity;
    }

    [Remote]
    [Delete]
    public async Task Delete([Service] IPersonDbContext personContext)
    {
        await personContext.DeleteAllPersons();
        await personContext.SaveChangesAsync();
    }
}
