using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Neatoo;
using Neatoo.RemoteFactory;
using Neatoo.Rules.Rules;
using Person.Ef;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace Person.DomainModel;

public partial interface IPersonModel : IEditBase
{
    // Not Empty - Properties auto-generated by BaseGenerator (Roslyn)
}

[Factory]
[Authorize<IPersonModelAuth>]
internal partial class PersonModel : EditBase<PersonModel>, IPersonModel
{
    public PersonModel(IEditBaseServices<PersonModel> editBaseServices,
        [Service] IUniqueNameRule uniqueNameRule) : base(editBaseServices)
    {
        RuleManager.AddRule(uniqueNameRule);
    }

    public partial int? Id { get; set; }

    [DisplayName("First Name")]
    [Required(ErrorMessage = "First Name is required")]
    public partial string? FirstName { get; set; }

    [DisplayName("Last Name")]
    [Required(ErrorMessage = "Last Name is required")]
    public partial string? LastName { get; set; }

    [DisplayName("Email Address")]
    public partial string? Email { get; set; }

    [DisplayName("Notes")]
    public partial string? Notes { get; set; }

    public partial IPersonPhoneModelList PersonPhoneModelList { get; set; }

    public partial DateTime Created { get; set; }
    public partial DateTime Modified { get; set; }

    public partial void MapFrom(PersonEntity personEntity);
    public partial void MapTo(PersonEntity personEntity);
    public partial void MapModifiedTo(PersonEntity personEntity);

    [Create]
    public async Task Create([Service] IAllRequiredRulesExecuted allRequiredRulesExecuted,
                    [Service] IPersonPhoneModelList personPhoneModelList)
    {
        this.Id = 1;
        this.Created = DateTime.Now;
        this.Modified = DateTime.Now;


        // ObjectInvalid until all Required properties have been updated at least once
        RuleManager.AddRule(allRequiredRulesExecuted);
        PersonPhoneModelList = personPhoneModelList;

        var personPhoneModel = await PersonPhoneModelList.AddPhoneNumber();
        personPhoneModel.PhoneNumber = "555-555-5555";

        personPhoneModel = await PersonPhoneModelList.AddPhoneNumber();
        personPhoneModel.PhoneNumber = "888-333-4444";
    }

    [Remote]
    [Fetch]
    public async Task<bool> Fetch([Service] IPersonContext personContext,
                                    [Service] IPersonPhoneModelListFactory personPhoneModelListFactory)
    {
        var personEntity = await personContext.Persons.FirstOrDefaultAsync(x => x.Id == 1);
        if (personEntity == null)
        {
            return false;
        }
        this.MapFrom(personEntity);
        this.PersonPhoneModelList = personPhoneModelListFactory.Fetch(personEntity.Phones);
        return true;
    }

    [Remote]
    [Insert]
    public async Task<PersonEntity> Insert([Service] IPersonContext personContext,
                                    [Service] IPersonPhoneModelListFactory personPhoneModelListFactory)
    {
        await personContext.DeleteAllPersons();

        var personEntity = new PersonEntity();
        personContext.Persons.Add(personEntity);
        this.MapTo(personEntity);
        personPhoneModelListFactory.Save(this.PersonPhoneModelList, personEntity.Phones);

        await personContext.SaveChangesAsync();
        return personEntity;
    }

    [Remote]
    [Update]
    public async Task<PersonEntity> Update([Service] IPersonContext personContext,
                                    [Service] IPersonPhoneModelListFactory personPhoneModelListFactory)
    {
        var personEntity = await personContext.Persons.FirstOrDefaultAsync(x => x.Id == this.Id);
        if (personEntity == null)
        {
            throw new KeyNotFoundException("Person not found");
        }

        this.MapModifiedTo(personEntity);

        personPhoneModelListFactory.Save(this.PersonPhoneModelList, personEntity.Phones);

        await personContext.SaveChangesAsync();
        return personEntity;
    }

    [Remote]
    [Delete]
    public async Task Delete([Service] IPersonContext personContext,
                                    [Service] IPersonPhoneModelListFactory personPhoneModelListFactory)
    {
        var personEntity = await personContext.Persons.FirstOrDefaultAsync(x => x.Id == this.Id);

        if (personEntity != null)
        {
            personContext.DeletePerson(personEntity);
            await personContext.SaveChangesAsync();
        }
    }
}
