using Neatoo;
using Neatoo.RemoteFactory;
using Neatoo.Rules;
using Neatoo.Rules.Rules;
using Person.Ef;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Person.DomainModel;

public enum PhoneType
{
    Home,
    Work,
    Mobile
}

public partial interface IPersonPhoneModel : IIdEditBase
{
    // Not Empty - Properties auto-generated by BaseGenerator (Roslyn)
    IPersonModel? ParentPersonModel { get; }
}

[Factory]
internal partial class PersonPhoneModel : IdEditBase<PersonPhoneModel>, IPersonPhoneModel
{
    [Create]
    public PersonPhoneModel([Service] IUniquePhoneNumberRule uniquePhoneNumberRule,
                    [Service] IUniquePhoneTypeRule uniquePhoneTypeRule,
        [Service] IEditBaseServices<PersonPhoneModel> services) : base(services)
    {
        RuleManager.AddRule(uniquePhoneNumberRule);
        RuleManager.AddRule(uniquePhoneTypeRule);
    }

    [Required(ErrorMessage = "Phone number type is required")]
    public partial PhoneType? PhoneType { get; set; }

    [DisplayName("Phone Number*")]
    [Required(ErrorMessage = "Phone number is required")]
    public partial string? PhoneNumber { get; set; }

    public IPersonModel? ParentPersonModel => this.Parent as IPersonModel;

    public partial void MapFrom(PersonPhoneEntity personPhoneEntity);
    public partial void MapTo(PersonPhoneEntity personPhoneEntity);

    [Fetch]
    public void Fetch(PersonPhoneEntity personPhoneEntity)
    {
        MapFrom(personPhoneEntity);
    }

    [Insert]
    [Update]
    public void Update(PersonPhoneEntity personPhoneEntity)
    {
        MapTo(personPhoneEntity);

        if(Id == null)
        {
            personPhoneEntity.PropertyChanged += HandleIdPropertyChanged;
        }
    }
}